### ISSUE TITLE
osx readarray

### ISSUE THREAD

**Issue by matti** [lee0c/kubectl-watch#2]
kubectl-watch: line 110: readarray: command not found

**Comment by lee0c** [comment]
Can you confirm what shell you are using? I am guessing this is due to a non-bash shell & am working on fixing it :)

**Comment by matti** [comment]
the script starts with `#!/bin/bash` (should start with `#!/usr/bin/env bash`)

but the problem seems to be this: https://stackoverflow.com/questions/23842261/alternative-to-readarray-because-it-does-not-work-on-mac-os-x

**Comment by lee0c** [comment]
Good point, I haven't focused on this in a bit so I wasn't even thinking of that. & I'll make that fix :)

Thanks for the link, I'll get it working without readarray.

**Comment by lee0c** [comment]
Finally fixed this. Slipped my mind for a while.
